name: hapi-api
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: akhileshns/heroku-deploy@v3.8.9
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: hapi-studio
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
